# Generated by Django 3.2.5 on 2021-07-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_boards', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=75),
        ),
    ]
