# Generated by Django 3.2.5 on 2021-07-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_boards', '0005_post_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=75),
        ),
    ]
